### PR TITLE
Add Simplified Chinese (zh-CN) translation

### PR DESCRIPTION
**Pull request by Crystal-RainSlide**

### CODE REVIEW

**Comment by joonas-fi** [comment]
Oh wow, thanks so much! :smile: 

I'll merge this soon. I would've done it now, but the HTML -> PDF engine I'm using doesn't seem to support Chinese glyphs (the text just comes up empty). I've to resolve it first so I can test this.

**Comment by Crystal-RainSlide** [comment]
([wkhtmltopdf](https://wkhtmltopdf.org/) supports Chinese)

**Comment by joonas-fi** [comment]
> ([wkhtmltopdf](https://wkhtmltopdf.org/) supports Chinese)

You're right. I just had to add the right fonts, [which was a bit of a hurdle running on Lambda](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4280#issuecomment-903521888)

**Comment by joonas-fi** [comment]
Thank you again for this! This is merged and live at https://joonas.fi/emergency-details-printout/

I'm considering making the translator credit an optional URL, do you want to link to your Twitter/GitHub/etc (pick just one) profile instead of just a username?

**Comment by Crystal-RainSlide** [comment]
Username is fine for me, plus I don't have any page that is good enough for this purpose yet~

**Pull request merged**
